development:
  adapter: postgresql
  encoding: unicode
  database: heroku_development
  pool: 5
  username: cs
  password: cs-kobi
  
test:
  adapter: postgresql
  encoding: unicode
  database: heroku_development
  pool: 5
  username: cs
  password: cs-kobi
  

